---
title: Historical Stock Exploration in SQL and R
author: Avery Rogers
date: '2021-06-02'
slug: historical-stock-exploration-in-sql-and-r
categories: []
tags: []
---

```{r}
# Loading libraries 
library(tidyverse)
library(lubridate)
library(httr)
library(jsonlite)
library(stringr)
library(sqldf)
```

```{r}
# Get S&P 500 names and industries

constituents_data <- read_csv("~/constituents_csv.csv")

constituents <- 
  constituents_data %>% 
  select(symbol = `Symbol`, sector = `Sector`)

constituents$symbol

constituents_comma_str <- paste(constituents$symbol, collapse=",")

constituents_comma_str

```

```{r}
sandp_100 <- "AAPL,ABBV,ABT,ACN,AGN,AIG,ALL,AMGN,AMZN,AXP,BA,BAC,BIIB,BK,BLK,BMY,C,CAT,CELG,CL,CMCSA,COF,COP,COST,CSCO,CVS,CVX,DD,DHR,DIS,DOW,DUK,EMC,EMR,EXC,F,FB,FDX,FOX,FOXA,GD,GE,GILD,GM,GOOG,GOOGL,GS,HAL,HD,HON,IBM,INTC,JNJ,JPM,KMI,KO,LLY,LMT,LOW,MA,MCD,MDLZ,MDT,MET,MMM,MO,MON,MRK,MS,MSFT,NEE,NKE,ORCL,OXY,PCLN,PEP,PFE,PG,PM,PYPL,QCOM,RTN,SBUX,SLB,SO,SPG,T,TGT,TWX,TXN,UNH,UNP,UPS,USB,USD,UTX,V,VZ,WBA,WFC"
```



```{r}

request_url = str_c(
  "http://api.marketstack.com/v1/eod?access_key=fc910231d068b033c010af5d25e705d1&symbols=",
  sandp_100,
  "&date_from=2020-02-05&date_to=2020-05-05",
  "&limit=10000"
)

request <- GET(request_url)

request$status_code

request

```

```{r}
stocks_data <- fromJSON(rawToChar(request$content))

stocks_data <- stocks_data$data

stocks <- as_tibble(stocks_data)

```

```{r}
stocks <- 
  stocks %>% 
  mutate(date = str_sub(date, 1, 10)) %>% 
  mutate(date = date(date))

stocks
```


```{r}
stocks %>% 
  ggplot(aes(date, close, group = symbol)) +
  geom_line()
```

```{r}
stocks %>% 
  group_by(symbol) %>% 
  summarize(close = mean(close)) %>% 
  top_n(close, n=3)
```
```{r}
stocks %>% 
  filter(!symbol %in% c("GOOG", "AMZN", "GOOGL")) %>% 
  ggplot(aes(date, close, group = symbol)) +
  geom_line() +
  geom_vline(xintercept = date("2020-03-09"), color = "blue", linetype = "dashed")
```

```{r}
stocks <- 
  stocks %>% 
  arrange(date) %>% 
  group_by(symbol) %>% 
  mutate(diff = (close - first(close, order_by = date)) / first(close, order_by = date)) %>% 
  ungroup() %>% 
  group_by(date) %>% 
  mutate(avg = mean(diff))

stocks
```

```{r}
stocks %>% 
  ggplot() +
  geom_line(aes(date, diff, group = symbol)) +
  geom_line(aes(date, avg), color = "orange", size = 1) +
  geom_line(data = stocks %>% filter(symbol == "AMZN"), aes(date, diff), color = "green") +
   geom_line(data = stocks %>% filter(symbol == "GILD"), aes(date, diff), color = "purple") +
  geom_hline(yintercept = 0, color = "red") +
  geom_vline(xintercept = date("2020-03-09"), color = "blue", linetype = "dashed") +
  geom_vline(xintercept = date("2020-03-12"), color = "blue", linetype = "dashed") +
  geom_vline(xintercept = date("2020-03-16"), color = "blue", linetype = "dashed")
```

GILD, in purple above, is the only stock that never dipped below it's February 5th value. GILD, or Gilead Sciences, is a biopharmaceutical company specializing in antiviral drugs, such as those used in the treatment of HIV and the various forms of hepatitis. 

```{r}
stocks %>% 
  filter(date == date("2020-05-05")) %>% 
  filter(diff > 0)
```
```{r}
stocks_industry <- 
  stocks %>% 
  left_join(constituents, by = "symbol")

stocks_industry
```
Now, let's aggregate by industry:

```{r}
stocks_ind_avg <- 
  stocks_industry %>% 
  filter(!is.na(sector)) %>% 
  group_by(sector, date) %>% 
  summarize(diff = mean(diff)) %>% 
  ungroup()

stocks_ind_avg
```
```{r}
stocks_ind_avg %>% 
  # mutate(sector = as_factor(sector)) %>% 
  mutate(sector = fct_reorder2(sector, date, diff)) %>% 
  ggplot(aes(date, diff, color = sector)) +
  geom_line()
```
```{r}
stocks_industry %>% 
  filter(sector %in% c("Health Care", "Communication Services")) %>% 
  ggplot(aes(date, diff, group=symbol, color=sector)) + 
  geom_line()
```

